baseurl: "https://s.4na.xyz/blog/"
title: "S--Minecraft.github.io"
languageCode: "jp"
copyright: "(C) 2015 S__Minecraft"
MetaDataFormat: "yaml"
taxonomies:
  tag: "tags"
  category: "categories"
author:
  name: "S__Minecraft"
paginate: 15
params:
  hpurl: "https://s.4na.xyz/"
pygmentscodefences: true
pygmentsstyle: "monokai"
