language: node_js
node_js:
- "0.12"
sudo: false
cache:
  directories:
  - node_modules
  - bower_components
  - "$HOME/gopath"
  - "$HOME/.nvm"
  - "$HOME/.cache/pip"
branches:
  only:
  - source
env:
  global:
  - GOPATH=$HOME/gopath
  - PATH=$HOME/gopath/bin:$PATH
  - GIT_COMMITTER_NAME="Travis CI"
  - GIT_COMMITTER_EMAIL=S--Minecraft@users.noreply.github.com
  - GIT_AUTHOR_NAME="Travis CI"
  - GIT_AUTHOR_EMAIL=S--Minecraft@users.noreply.github.com
  - secure: L7awusiT3hVcb660hJplgkDn0UfJD/5ptU8idRjKb4tcsZSkwI8mrQwBR3ABlm/Lsqr212RyWKboQb0n2TZhMUHW0fhmlBClHw9CbTof7YMUwt7Dt65P//enj9Znzeg77k4TuxBuXm+apk+9P7iGsASUEsvF3xUqWXvlDXkk7qdgO+jSpnG8Vyx1NRpYvPlQU+P+nrNEW/PaWtDCR51gRK57zgARzXQIyAUY9dqnHrRAv91MpVsd8Un8AryUrBjiM7QGaIO6rgdz1+NxFe64L9LrRIaoERNt7LSDwkqrCGkBe346aUUH8MZ0MrH4syGe7PPINA3XUisRSUv2gG6RjQMTxBd3UlnkXwP2KhsL5mCahM/BR/4TMor06o+k//lYxXsVTrNZU43i/6C0oO097wNZhxZBXUpo3Bj76SadpaU8q1WoJRk8tGD+07aWjcPLnJHJnFS/9wPR97B5PkwzHFu+anD3girqUA6i8Hh9B7BVE1GShTGr5zo9nWA27h2Wt0zRywMXYrqGhbwKo54trA+kywm4UB0AHooadkqWIhSgidnff6A2G5ZaB4G2RyO+bGUb48AfXLKLcKSS2EenaWf0Fi2l951ROwvNA7QhJ2YXcTaWSd/vgp1wddaJSIrh0bQTcnSzRGsKfYBwJzcW72Kjh8sQ5T8UKCuNen+v+CE=
install:
  - go get -v github.com/spf13/hugo
  - sudo pip install Pygments
before_script:
- echo "Version"
- go version
- node -v
- hugo version
- echo "-------"
- npm install
- node_modules/.bin/bower install
- git clone -b master https://github.com/S--Minecraft/s--minecraft.github.io release
- pushd release
- git checkout master
- popd
script:
- node_modules/.bin/gulp release
after_success:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/travis.key\n" >> ~/.ssh/config
- openssl aes-256-cbc -k "$SERVER_KEY" -in travis.enc -d -a -out travis.key
- cp travis.key ~/.ssh/
- chmod 600 ~/.ssh/travis.key
- ssh-add travis.key
- ssh -T git@github.com
- cd release
- git add --all
- git commit -m "[Travis CI] $TRAVIS_COMMIT"
- '[ "$TRAVIS_PULL_REQUEST" == "false" ] && git push git@github.com:S--Minecraft/s--minecraft.github.io.git master'
